### ISSUE TITLE
Battlenettag error

### ISSUE THREAD

**Issue by DeathlyKnife** [ptoast/FlapJack-Cogs#8]
I cant use my battlenet gamertag because my # has 5 numbers behind it instead of 4.
can this be fixed so i can use my battlenet account.

**Comment by ptoast** [comment]
Thank you.  I completely missed the memo that Blizzard was creating 5 digit battletags. Apparently it happened several years ago. I will patch this immediately!

**Comment by ptoast** [comment]
Issue has been fixed with commit https://github.com/ptoast/FlapJack-Cogs/commit/f24bb3631dd4e9640181b2fa2345dbb861e98af9. Please update and reload the blizzard.py cog for the changes to take effect.

4 and 5 digit battletags are now accepted.

Thank you for reporting this! Please reply here or create a new issue if you have further problems.

**Comment by DeathlyKnife** [comment]
thnx for the fast responce and fix i will update it asap.
